version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-tests-coverage:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
            - run: bash <(curl -s https://codecov.io/bash)
workflows:
  build-tests-coverage:
    jobs:
      - build-tests-coverage
